apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-api-data
  namespace: k8s-api
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
