# Generated by Django 6.1 on 2026-08-22 18:54

import backups.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0002_backup_app_source_path_public_id"),
        ("clusters", "0004_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=backups.models.generate_schedule_public_id,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("source_path", models.CharField(max_length=500)),
                ("cron_expression", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_schedules",
                        to="clusters.app",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
