"""
Django settings for k8s_api project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to an insecure dev-only key so local `runserver` keeps working
# without an .env file; production (k8s Secret) always overrides this.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-72@xw(px1=9+bsgf%x#+$*o*hm7l+sj*9@l#on!9x2&=y_nt_$',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'clusters',
    'backups',
    'django_extensions',

]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'k8s API',
    'DESCRIPTION': 'API for managing k8s clusters, namespaces, apps, and backups.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # /docs/ and /schema/ default to public (AllowAny) -- restrict to
    # logged-in admin/staff users only, not the whole internet.
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'k8s_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'k8s_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DATA_DIR separates persistent state (db, backup dumps) from BASE_DIR (the
# source tree, baked into the image) -- in k8s a PVC is mounted at DATA_DIR
# so the container filesystem itself can stay ephemeral/read-write-from-image.
DATA_DIR = Path(os.environ.get('DATA_DIR', BASE_DIR))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Celery
# https://docs.celeryq.dev/en/stable/userguide/configuration.html

# localhost:6380 is this project's local-dev default (see requirements.txt
# and README instructions); overridden in docker-compose.yml so each service
# reaches Redis by its container name instead ("localhost" inside a
# container refers to that container itself, not a sibling service).
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6380/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6380/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Sweeps pending/running backups older than this and marks them failed (doc:
# handling a backup stuck pending for 24h -- worker down / queue stuck / task
# died silently). Runs both on this schedule and inline on every status/list
# read, see backups.tasks.sweep_stale_backups.
BACKUP_STALE_TIMEOUT = timedelta(hours=24)
CELERY_BEAT_SCHEDULE = {
    'mark-stale-backups': {
        'task': 'backups.tasks.mark_stale_backups',
        'schedule': timedelta(minutes=30),
    },
    # Cron granularity is a minute, so this has to tick at least that often
    # to not miss/delay a schedule's slot; see backups.tasks.run_due_backup_schedules.
    'run-due-backup-schedules': {
        'task': 'backups.tasks.run_due_backup_schedules',
        'schedule': timedelta(minutes=1),
    },
    # Reconciles App.status against real Deployment state in Kubernetes;
    # see clusters.tasks.sync_app_status.
    'sync-app-status': {
        'task': 'clusters.tasks.sync_app_status',
        'schedule': timedelta(minutes=2),
    },
}

# Named "backup_dumps" rather than "backups" because BASE_DIR already
# contains the `backups` Django app package -- storing files there would
# collide with the app's own source directory.
BACKUP_DIR = DATA_DIR / 'backup_dumps'
