# Generated by Django 6.1 on 2026-08-18 15:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Name must be a valid Kubernetes namespace name (lowercase alphanumeric and "-", must start/end with alphanumeric).',
                                regex="^[a-z0-9]([-a-z0-9]*[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("uid", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namespaces",
                        to="clusters.cluster",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("cluster", "name")},
            },
        ),
    ]
