# Generated by Django 6.1 on 2026-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0002_namespace"),
    ]

    operations = [
        migrations.AddField(
            model_name="namespace",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("deleting", "Deleting")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="namespace",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
