# Generated by Django 6.1 on 2026-08-19 07:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0003_namespace_status_namespace_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Name must be a valid Kubernetes namespace name (lowercase alphanumeric and "-", must start/end with alphanumeric).',
                                regex="^[a-z0-9]([-a-z0-9]*[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Name must be a valid Kubernetes namespace name (lowercase alphanumeric and "-", must start/end with alphanumeric).',
                                regex="^[a-z0-9]([-a-z0-9]*[a-z0-9])?$",
                            )
                        ],
                    ),
                ),
                ("image", models.CharField(default="nginx:latest", max_length=255)),
                ("replicas", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deleting", "Deleting")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        to="clusters.cluster",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("cluster", "namespace", "name")},
            },
        ),
    ]
