# Generated by Django 6.1 on 2026-08-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0004_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deleting", "Deleting"),
                    ("missing", "Missing"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
