# Generated by Django 6.1 on 2026-08-30 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0006_app_owner_namespace_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_clusters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="is_accessible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="namespace",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_namespaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="namespace",
            name="is_accessible",
            field=models.BooleanField(default=True),
        ),
    ]
